thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
30246664,30246664,null,1,0,Thu May 14 20:23:00 EDT 2015,4901427,"<p>I am trying the Internet of Things Foundation Starter boilerplate in Bluemix. Here are the steps I am following:</p>		<ol>	<li>Create a new app using the boilerplate</li>	<li>Once the app is up, I go to the URL and see the NodeRED home page</li>	<li>I click on the button to take me to the NodeRED editor</li>	<li>In another browser window I have the IoT Sensor available here: <a href="https://quickstart.internetofthings.ibmcloud.com/iotsensor/" rel="nofollow">https://quickstart.internetofthings.ibmcloud.com/iotsensor/</a> up and running</li>	<li>I configure the "IoT App In Node" with the address of my IoT sensor. I have removed the ":"'s and have made the letters lowercase.	<ol start="6">	<li>When I click Deploy in the NodeRED editor, I see the following error:  "Error: Lost connection to server"</li>	</ol></li>	</ol>		<p>After step 2 I already see these errors in the log:</p>		<pre><code>2015-05-14T16:05:10.31-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:10.316] [TRACE] [default] - â†?[39m1 iot-2/type/+/id//evt/+/fmt/json	2015-05-14T16:05:10.31-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:10.316] [TRACE] [default] - â†?[39mResubscribing:	2015-05-14T16:05:10.31-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:10.318] [TRACE] [default] - â†?[39mRetry count = 1	2015-05-14T16:05:12.32-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:12.320] [TRACE] [default] - â†?[39mCONNECTED......:	2015-05-14T16:05:12.32-0400 [App/0]   OUT Subscription Count = 1	2015-05-14T16:05:12.32-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:12.320] [TRACE] [default] - â†?[39m1 iot-2/type/+/id//evt/+/fmt/json	2015-05-14T16:05:12.32-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:12.320] [TRACE] [default] - â†?[39mResubscribing:	2015-05-14T16:05:12.32-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:12.322] [TRACE] [default] - â†?[39mRetry count = 1	2015-05-14T16:05:13.32-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:13.328] [TRACE] [default] - â†?[39mCONNECTED......:	2015-05-14T16:05:13.32-0400 [App/0]   OUT Subscription Count = 1	</code></pre>		<p>After step 5 after the error happens, I see the following error:</p>		<pre><code>2015-05-14T16:05:17.35-0400 [App/0]   OUT â†?[34m[2015-05-14 20:05:17.355] [TRACE] [default] - â†?[39m1 iot-2/type/+/id//evt/+/fmt/json	2015-05-14T16:05:17.35-0400 [App/0]   OUT 14 May 20:05:17 - [red] Uncaught Exception:	2015-05-14T16:05:17.35-0400 [App/0]   OUT 14 May 20:05:17 - Error: This method cannot be called until MQTT client has been initialized (see connectMqtt() method)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at IoTAppClient.checkMqtt (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/iotclient/application/IoTAppClient.	js:340:9)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at MqttClient.&lt;anonymous&gt; (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/iotclient/application/IoTAppClient.	js:120:9)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at MqttClient.emit (events.js:117:20)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at MqttClient._handleConnack (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/iotclient/node_modules/mqtt/lib/	client.js:521:10)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at Connection.&lt;anonymous&gt; (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/iotclient/node_modules/mqtt/lib/cli	ent.js:191:10)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at Connection.emit (events.js:95:17)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at Connection._write (/home/vcap/app/node_modules/node-red-contrib-scx-ibmiotapp/node_modules/iotclient/node_modules/mqtt/lib/connecti	on.js:176:12)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at doWrite (_stream_writable.js:226:10)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at writeOrBuffer (_stream_writable.js:216:5)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at Connection.Writable.write (_stream_writable.js:183:11)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at write (_stream_readable.js:602:24)	2015-05-14T16:05:17.35-0400 [App/0]   OUT     at flow (_stream_readable.js:611:7)	2015-05-14T16:05:17.38-0400 [App/0]   ERR	2015-05-14T16:05:17.41-0400 [RTR]     OUT testiotsd.mybluemix.net - [14/05/2015:20:04:40 +0000] "GET /red/comms HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Ge	cko/20100101 Firefox/31.0" 75.126.70.46:60509 x_forwarded_for:"75.126.70.46" vcap_request_id:231a532e-d89e-4236-49e7-7d00a803cd18 response_time:MissingFinishedAt app_id:4cc323b6-d2	48-4fd3-b8ac-c046539a6c2b	2015-05-14T16:05:17.48-0400 [API]     OUT App instance exited with guid 4cc323b6-d248-4fd3-b8ac-c046539a6c2b payload: {"cc_partition"=&gt;"default", "droplet"=&gt;"4cc323b6-d248-4fd3-b8a	c-c046539a6c2b", "version"=&gt;"2778c52b-ac6d-4845-8077-761927982233", "instance"=&gt;"288976a131434a34b033c7d1fd0e812e", "index"=&gt;0, "reason"=&gt;"CRASHED", "exit_status"=&gt;1, "exit_descrip	tion"=&gt;"app instance exited", "crash_timestamp"=&gt;1431633917}	</code></pre>		<p>Now if I restart the app everything just works fine.  But I can recreate the above scenario consistently every time with these steps:</p>		<ol>	<li>create new app from boilerplate</li>	<li>go to NodeRED editor</li>	<li>configure IoT in-node</li>	<li>deploy</li>	<li>get error</li>	<li>stop and start runtime </li>	<li>all works </li>	</ol>		<p>Need help figuring out why this is happening and how to prevent it.</p>		<p>Thanks</p>	"
30246664,48604655,30246664,3,0,Fri May 15 05:33:00 EDT 2015,4901427,"Here is the flow: https://www.dropbox.com/s/m0wbostj8lh76na/flow.png?dl=1		And here is the configuration of my IBM IoT App In node: https://www.dropbox.com/s/jiewh2c1oe8htua/IoTappInNode.png?dl=1"
30246664,48600614,30246664,3,0,Fri May 15 01:24:00 EDT 2015,3817025,"Can you edit your post with a screen cap of your flow? Also can you post a screen cap for the config of the iot node?"
30246664,48617041,30246664,3,0,Fri May 15 11:50:00 EDT 2015,4454969,"Shahir, I get this same error.  I have seen it for a few weeks, I will check with the dev team to see why it may be happening. It seems to automatically restart itself but does give the lost connection error."
30246664,30353069,30246664,2,1,Wed May 20 14:46:00 EDT 2015,4920982,"<p>Shahir<br>	A permanent fix has been uploaded in the npmjs and Internet of Things Foundation Starter boilerplate of Bluemix, which resolves this issue.</p>	"
30246664,48944180,30353069,3,0,Mon May 25 00:27:00 EDT 2015,4901427,"Thanks Amit.  I have tested it and it works fine now.  Thanks again."
