thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
30878659,30878659,null,1,3,Tue Jun 16 21:35:00 EDT 2015,644109,"<p>I have a Node-RED application that is bound to an IOT Foundation (iotf) service. I can receive events from devices and handle them appropriately.</p>		<p>However, I am now interested in sending commands back to my devices and am having some problems. Nothing is showing up at the device, but by creating an IOTF in node, I can confirm that the command is passing through iotf.</p>		<p>I can definitely get commands to pass through iotf using pure python, as the follow code works well:</p>		<p><strong>Client code:</strong></p>		<pre><code>#!/usr/bin/python		import ibmiotf.device	from time import sleep		options = {	  "org": "cgmncc",	  "type": "table",	  "id": "b827eb764b7a",	  "auth-method": "token",	  "auth-token": "redacted"	}		def myCommandCallback(cmd):	  print('inside command callback')	  print cmd		def main():	  client = ibmiotf.device.Client(options)	  client.connect()	  client.commandCallback = myCommandCallback	  while True:	    sleep(1)		if __name__ == "__main__":	  main()	</code></pre>		<p><strong>Application code:</strong></p>		<pre><code>#!/usr/bin/python		import ibmiotf.application		options = {	  "org": "redacted",	  "id": "python app",	  "auth-method": "apikey",	  "auth-key": "redacted",	  "auth-token": "redacted"	}		try:	  client = ibmiotf.application.Client(options)	  client.connect()	  client.publishCommand('table', 'b827eb764b7a', 'test')	  client.disconnect()	except ibmiotf.ConnectionException as e:	  print e	</code></pre>		<p>Whenever I run the application code, I see the following output:</p>		<pre><code>root@raspberrypi ~ # ./app.py 	inside command callback	&lt;ibmiotf.device.Command instance at 0x14e8490&gt;	</code></pre>		<p>I have a Node-RED iotf output node configured as shown below, but when I trigger the flow, the command callback function doesn't trigger!</p>		<p><img src="https://i.stack.imgur.com/77h87.png" alt="enter image description here">	<img src="https://i.stack.imgur.com/2V7Ve.png" alt="enter image description here"></p>		<p>I'm thinking there maybe something wrong either with trying to use a timestamp trigger to fire the command, or with the way I've configured the output node itself -- any suggestions or advice would be appreciated!</p>	"
30878659,49819749,30878659,3,1,Wed Jun 17 11:30:00 EDT 2015,4454969,"Your device type "table" seems a bit odd. Is that how you registered your device?   Please provide your org so I can check your registered devices."
30878659,49839488,30878659,3,0,Wed Jun 17 19:08:00 EDT 2015,644109,"Thanks @ValerieLampkin	You can take a look, my org is cgmncc.	I can definitely send commands to the device using a python application registered to the same organization, but whenever I try to do the same from Node-RED, nothing is showing up on the device. I'm not sure if the commands are even making it to the IOT foundation (historian doesn't appear to have an API for seeing command messages)."
30878659,30916143,30878659,2,2,Thu Jun 18 13:03:00 EDT 2015,4920982,"<p>A simple test to check if the commands are reaching IBM IoT Foundation is - developing another flow having an IoT App In node which subscribes to the commands. I am attaching the Node-RED flow for the same here </p>		<p><div class="snippet" data-lang="js" data-hide="false" data-console="false" data-babel="false">	<div class="snippet-code">	<pre class="snippet-code-html lang-html prettyprint-override"><code>[	{	    "id": "40560f8b.30693",	    "type": "ibmiot in",	    "authentication": "boundService",	    "apiKey": "",	    "inputType": "cmd",	    "deviceId": "b827eb764b7a",	    "applicationId": "",	    "deviceType": "table",	    "eventType": "",	    "commandType": "test",	    "format": "string",	    "name": "IBM IoT App In",	    "service": "registered",	    "allDevices": false,	    "allApplications": "",	    "allDeviceTypes": false,	    "allEvents": "",	    "allCommands": false,	    "allFormats": false,	    "x": 268,	    "y": 171,	    "z": "6bd610b9.7b40a",	    "wires": [	        [	            "2f9b9c00.8b7ba4"	        ]	    ]	},	{	    "id": "2f9b9c00.8b7ba4",	    "type": "debug",	    "name": "",	    "active": true,	    "console": "false",	    "complete": "false",	    "x": 493,	    "y": 195,	    "z": "6bd610b9.7b40a",	    "wires": []	}	]</code></pre>	</div>	</div>	</p>		<p>It would appear this way in the workspace.<br>	<img src="https://i.stack.imgur.com/wkowS.png" alt="enter image description here">  </p>		<p>After you have added this flow, you can test the device command publishing from the same workspace.<br>	Can you please try this? Since you would now have 2 debug nodes, you should be able to see the same timetamp output twice. I have tried the same flow, with the same details (except the organization) and it works fine.   </p>		<p>Thanks and Regards<br>	Amit M Mangalvedkar</p>	"
30878659,50002410,30916143,3,0,Mon Jun 22 17:29:00 EDT 2015,644109,"Hi Amit, that's the entire device code. I don't see any way to set the command type from the documentation.	https://docs.internetofthings.ibmcloud.com/libraries/python_cli_for_devices.html#handling-commands		Please advise!"
30878659,49887140,30916143,3,0,Thu Jun 18 20:26:00 EDT 2015,644109,"Hi @amit-mangalvedkar thanks for the response.	I did try as you suggest and do see the timestamp twice in the output. So this tells me that the command is indeed making it through the IOT Foundation. I am now going to boot up my Raspberry Pi and reconnect it to the IOT Foundation to see if it'll receive the command as well."
30878659,49889462,30916143,3,0,Thu Jun 18 21:49:00 EDT 2015,644109,"I updated the original question with the code that I'm running on the device, it's still not receiving any commands as far as I can tell!"
30878659,49933909,30916143,3,1,Sat Jun 20 03:47:00 EDT 2015,4920982,"In the device code that you had pasted earlier, I am unable see any entry for the command type getting set to "test". Could you please post the entire client code (while just masking the auth token)?"
30878659,54876982,30916143,3,0,Thu Nov 05 15:36:00 EST 2015,644109,"Honestly it was so long ago I cannot recall what it was that got me over the hurdle, but I did indeed get the thing to work! I'm going to mark your answer as correct, as it did lead me to the solution...... whatever it was <blush/>"
30878659,54682554,30916143,3,1,Sat Oct 31 01:52:00 EDT 2015,4920982,"I completely missed this comment and although more than 4 months have passed, I would like to know if this problem still persists."
30878659,30999106,30878659,2,1,Tue Jun 23 09:35:00 EDT 2015,4920982,"<p>I tried the following code</p>		<pre><code>#!/usr/bin/python		import ibmiotf.device	from time import sleep		options = {	  "org": "uguhsp",	  "type": "iotsample-raspberry",	  "id": "00aabbccde03",	  "auth-method": "token",	  "auth-token": "MASKED"	}		def myCommandCallback(cmd):	  print('inside command callback')	  print cmd		def main():	  client = ibmiotf.device.Client(options)	  client.connect()	  client.commandCallback = myCommandCallback	  while True:	    sleep(1)		if __name__ == "__main__":	  main()	</code></pre>		<p>which is essentially similar code as yours.<br>	And I am able to publish the commands to reach the device.  </p>		<p>Can you please confirm if only 1 device (or simulated device) is using the device credentials and that the credentials are not being shared by multiple devices (either physical device or simulated device)?   </p>		<p>Thanks and Regards<br>	Amit M Mangalvedkar  </p>	"
