thread_ID, Id, ParentId, PostType, Score, CreationDate, OwnerID, Body
35103434,35103434,null,1,3,Sat Jan 30 15:19:00 EST 2016,4361588,"<p>I did the following tutorial to connect my Raspberry Pi with an application on Bluemix using the IoT Foundation:</p>		<p><a href="https://developer.ibm.com/bluemix/2015/04/02/tutorial-using-a-raspberry-pi-python-iot-twilio-bluemix/" rel="nofollow">https://developer.ibm.com/bluemix/2015/04/02/tutorial-using-a-raspberry-pi-python-iot-twilio-bluemix/</a></p>		<p>I had everything up and running except the client.py (step 36 in the tutorial). I got the following error message:</p>		<pre><code>client.py:9: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.	  GPIO.setup(17, GPIO.OUT)	Traceback (most recent call last):	  File "client.py", line 23, in &lt;module&gt;	    options = ibmiotf.application.ParseConfigFile("/home/pi/device.cfg")	  File "/usr/local/lib/python2.7/dist-packages/ibmiotf/application.py", line 501, in ParseConfigFile	    appType = parms.get(sectionHeader, "type", "standalone")	  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get	    raise NoOptionError(option, section)	ConfigParser.NoOptionError: No option 'type' in section: 'application'	</code></pre>		<p>I found out the the error came from the missing "type" section in the config file (device.cfg). </p>		<p>The file structure listed in step 35 of the tutorial doesn't say, that you need a "type". I used the device type (raspberrypi) that I created before in the IoT Foundation.</p>		<p>Now I did connect to the IoT Foundation successfully.</p>		<p>The problem that I have now is, that nothing is happening when I either press the button on my Raspberry Pi or the "Turn light on/off" buttons of the web application.</p>		<p>If I check the logs of the python app using "./cf logs myappname -recent" I get the following output:</p>		<pre><code>2016-01-29T08:38:49.10+0100 [App/0]      OUT on	2016-01-29T08:38:49.10+0100 [App/0]      ERR 75.126.37.74 - - [29/Jan/2016 07:38:49] "POST /light/on HTTP/1.1"; 302 -	2016-01-29T08:38:49.34+0100 [App/0]      ERR 75.126.52.20 - - [29/Jan/2016 07:38:49] "GET / HTTP/1.1"; 200 -	2016-01-29T08:38:49.56+0100 [RTR/1]      OUT myappname.mybluemix.net - [29/01/2016:07:38:49 +0000] "GET / HTTP/1.1" 200 0 751 "http://myappname.mybluemix.net/&amp;quot; ";Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36" 108.168.250.151:39460 x_forwarded_for:&amp;quot;46.5.2.236"x_forwarded_proto:"http&amp;quot; vcap_request_id:myrequestid response_time:0.31228492 app_id:myapp_id x_global_transaction_id:mytransactionid;	2016-01-29T08:40:08.32+0100 [App/0]      OUT off	2016-01-29T08:40:08.33+0100 [App/0]      ERR 75.126.37.74 - - [29/Jan/2016 07:40:08] "POST /light/off HTTP/1.1" 302 -	2016-01-29T08:40:08.51+0100 [App/0]      ERR 75.126.23.243 - - [29/Jan/2016 07:40:08] "GET / HTTP/1.1" 200 -`	</code></pre>		<p>The writer of the tutorial, Jeff, said that I should double check that the Pi and the app in Bluemix are both listening on the same topic. And in the IoT service I should be able to see messages coming through.</p>		<p>I don't know what this means or how I do this.</p>		<p>We already had an discussion about my problems in the comment section of the youtube video of the blog post (<a href="https://www.youtube.com/watch?v=YHDhn5hGnn8" rel="nofollow">https://www.youtube.com/watch?v=YHDhn5hGnn8</a>) and Jeff told me we should move to StackOverflow with it (makes sense).</p>		<p>I appreciate your help.</p>		<p>// edit for additional information //	This is the output I get on the Pi, when I start the application:	sudo python client.py</p>		<pre><code>2016-02-01 14:36:23,221   ibmiotf.application.Client  WARNING Unable to encrypt messages because TLSv1.2 is unavailable (MQTT over SSL requires at least Python v2.7.9 or 3.4 and openssl v1.0.1)	2016-02-01 14:36:23,716   ibmiotf.application.Client  INFO    Connected successfully: A:69wm3f:aaaafdsfsd45641safsda2313	</code></pre>		<p>If I press the on/off buttons for the first time after the client has started I get the following output on the Pi:</p>		<pre><code>Exception in thread Thread-1:	Traceback (most recent call last):	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner	    self.run()	  File "/usr/lib/python2.7/threading.py", line 505, in run	    self.__target(*self.__args, **self.__kwargs)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2287, in _thread_main	    self.loop_forever()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1261, in loop_forever	    rc = self.loop(timeout, max_packets)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 811, in loop	    rc = self.loop_read(max_packets)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1073, in loop_read	    rc = self._packet_read()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1475, in _packet_read	    rc = self._packet_handle()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1943, in _packet_handle	    return self._handle_publish()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2118, in _handle_publish	    self._handle_on_message(message)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2268, in _handle_on_message	    t[1](self, self._userdata, message)	  File "/usr/local/lib/python2.7/dist-packages/ibmiotf/application.py", line 423, in __onDeviceEvent	    if self.deviceEventCallback: self.deviceEventCallback(event)	  File "client.py", line 17, in myCommandCallback	    command = cmd.payload["d"]["command"]	TypeError: string indices must be integers, not str	</code></pre>		<p>It looks like the messages from the IoT Foundation are reaching the client.</p>		<p>I set the following IDs on the IoT Foundation, the environment variable of the Bluemix Python app and on the Raspberry Pi:</p>		<ul>	<li>IoT Foundation ID:   afdsfsd45641safsda2313</li>	<li>Bluemix Python app ID:   afdsfsd45641safsda2313</li>	<li>Raspberry Pi ID in device.cfg: afdsfsd45641safsda2313</li>	</ul>		<p>All three IDs are the same.</p>		<p>// edit 2 //	Logging output after adding the print cmd statements from the comment section:</p>		<pre><code>&lt;ibmiotf.application.Event instance at 0x76526738&gt;	light	{"command": "on"}	</code></pre>		<p>Stacktrace after changing </p>		<p><code>command = cmd.payload["d"]["command"]</code></p>		<p>to</p>		<p><code>command = cmd.payload["command"]</code></p>		<pre><code>Exception in thread Thread-1:	Traceback (most recent call last):	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner	    self.run()	  File "/usr/lib/python2.7/threading.py", line 505, in run	    self.__target(*self.__args, **self.__kwargs)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2287, in _thread_main	    self.loop_forever()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1261, in loop_forever	    rc = self.loop(timeout, max_packets)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 811, in loop	    rc = self.loop_read(max_packets)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1073, in loop_read	    rc = self._packet_read()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1475, in _packet_read	    rc = self._packet_handle()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1943, in _packet_handle	    return self._handle_publish()	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2118, in _handle_publish	    self._handle_on_message(message)	  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2268, in _handle_on_message	    t[1](self, self._userdata, message)	  File "/usr/local/lib/python2.7/dist-packages/ibmiotf/application.py", line 423, in __onDeviceEvent	    if self.deviceEventCallback: self.deviceEventCallback(event)	  File "client.py", line 18, in myCommandCallback	    command = cmd.payload["command"]	TypeError: string indices must be integers, not str	</code></pre>	"
35103434,57964829,35103434,3,0,Mon Feb 01 02:24:00 EST 2016,3817025,"To debug this we need to ensure the Pi is getting the IoT Foundation messages.  There could be 2 issues here...  The message queue topic is wrong or a connection error.  When you start the app on the Pi what output is displayed?  Also when you send turn the light on and off from Bluemix what output is displayed on the Pi?  Additionally, what is the device ID you have set in Bluemix and on the Pi?  I have a feeling the message topics are not matching up.  Post the updated info in your question above."
35103434,57983709,35103434,3,0,Mon Feb 01 13:44:00 EST 2016,4361588,"I added the information to my post."
35103434,57983896,35103434,3,0,Mon Feb 01 13:48:00 EST 2016,3817025,"So we are making progress...  We need to debug on what is going on in `client.py`.  Before line 17 add the following and re-run `client.py`.		`print cmd.payload`"
35103434,57984675,35103434,3,0,Mon Feb 01 14:07:00 EST 2016,4361588,"I added `print cmd.payload` after "print command" and before `if command == "on"`. The output didn't change. I get the same error message if I press one of the turn lights on/off buttons."
35103434,57984750,35103434,3,0,Mon Feb 01 14:09:00 EST 2016,3817025,"Sorry add `print cmd` on line 14. https://github.com/IBM-Bluemix/python-iot-raspberry-pi/blob/master/client.py#L14"
35103434,57984886,35103434,3,0,Mon Feb 01 14:11:00 EST 2016,4361588,"`<ibmiotf.application.Event instance at 0x7658c760>` followed by the stacktrace posted above."
35103434,57984988,35103434,3,0,Mon Feb 01 14:13:00 EST 2016,3817025,"Ok lets add a bit more logging. After the log statement you just added lets add the following couple more.  `print cmd.event`.  `print cmd.payload`."
35103434,57985048,35103434,3,0,Mon Feb 01 14:15:00 EST 2016,4361588,"`<ibmiotf.application.Event instance at 0x76541738>	light	{"command": "on"}`. That actually looks good to me?"
35103434,57985459,35103434,3,0,Mon Feb 01 14:23:00 EST 2016,3817025,"Let us [continue this discussion in chat](http://chat.stackoverflow.com/rooms/102252/discussion-between-jeff-sloyer-and-jenkins)."
35103434,35132827,35103434,2,2,Mon Feb 01 14:18:00 EST 2016,3817025,"<p>Turns out the IBM IoT Foundation library changed in the way it parses JSON...</p>		<p>Change <a href="https://github.com/IBM-Bluemix/python-iot-raspberry-pi/blob/master/client.py#L15" rel="nofollow">line 15</a></p>		<pre><code>command = cmd.payload["d"]["command"]	</code></pre>		<p>to </p>		<pre><code>payload = json.loads(cmd.payload)	command = payload["command"]	</code></pre>	"
35103434,57985285,35132827,3,0,Mon Feb 01 14:20:00 EST 2016,4361588,"The stacktrace is still the same (except that now the line is called `command = cmd.payload["command"]` at the end of the stack)"
35103434,57985380,35132827,3,0,Mon Feb 01 14:22:00 EST 2016,3817025,"What is the current stacktrack now?"
35103434,57985555,35132827,3,0,Mon Feb 01 14:25:00 EST 2016,4361588,"I edited my post. Is there any possibility to use a chat?"
35103434,57985569,35132827,3,0,Mon Feb 01 14:25:00 EST 2016,3817025,"Please goto http://chat.stackoverflow.com/rooms/102252/discussion-between-jeff-sloyer-and-jenkins"
35103434,35674637,35103434,2,0,Sat Feb 27 19:48:00 EST 2016,4033049,"<p>I add one line more "json.dumps", its worked for me.</p>		<pre><code>dataraw   = json.dumps(cmd.data)	payload = json.loads(dataraw)	command = payload["command"]	</code></pre>		<p>Best regards</p>	"
